spring.application.name=SpringAIDemo




spring.ai.model.chat=google-genai

spring.ai.google.genai.api-key=<your google studio api key>

spring.ai.google.genai.chat.model=gemini-3.5-flash

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=qwen3:8b